title: Colin Carlson
author: Colin Carlson
email: colincarlson01@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
instagram_username: xxcolinkingxx # DO NOT include the @ character, or else the build will fail!
github_username: xxcolinkingxx   # DO NOT include the @ character, or else the build will fail!
tiktok_username: Panzersoldat

show_excerpts: true # set to false to remove excerpts on the homepage
