title: Colin Carlson
author: Colin Carlson
email: colincarlson01@gmail.com
theme: jekyll-theme-
description: > # this means to ignore newlines until "baseurl:"
  This is an amazing description for my website! :-)

# social links
instagram_username: xxcolinkingxx # DO NOT include the @ character, or else the build will fail!
github_username: xxcolinkingxx   # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
